stdClass Object
(
    [s] => 1
    [d] => Array
        (
            [0] => stdClass Object
                (
                    [intangible] => 
                    [assetCost] => 20000000
                    [notes] => 
                    [lastJournalDateView] => 14 Dec 2023
                    [depreciationMethod] => STRAIGHTLINE
                    [departmentId] => 
                    [stockOpnameResult] => 
                    [optLock] => 2
                    [exchangeInvoice] => 
                    [depreciationAccountId] => 125
                    [receiveItem] => 
                    [rollOver] => 
                    [currentStartDateView] => 14 Dec 2023
                    [manufactureOrder] => 
                    [number] => FAA.2023.12.00003
                    [quantityDisposed] => 0
                    [itemAdjustment] => 
                    [draft] => 
                    [depreciationRate] => 25
                    [id] => 101
                    [fiscalFa] => 
                    [transDateView] => 14 Dec 2023
                    [periodEnd] => 
                    [workOrder] => 
                    [branchId] => 50
                    [quantityAvailable] => 1
                    [assetTransfer] => 
                    [salesInvoice] => 
                    [billOfMaterial] => 
                    [stockOpnameOrder] => 
                    [purchaseInvoice] => 
                    [estimatedLifeMonth] => 0
                    [usageDateView] => 14 Dec 2023
                    [salesOrder] => 
                    [transferOrder] => 
                    [fixedAssetEdited] => 
                    [salesQuotation] => 
                    [employeePayment] => 
                    [faTypeId] => 51
                    [expenseAccrual] => 
                    [salesReturn] => 
                    [purchaseRequisition] => 
                    [processStages] => 
                    [bankTransfer] => 
                    [finishedGoodSlip] => 
                    [journalId] => 3802
                    [purchasePayment] => 
                    [jobOrder] => 
                    [description] => MOBIL VARIO
                    [otherDeposit] => 
                    [otherPayment] => 
                    [costDistribution] => 
                    [customerClaim] => 
                    [journal] => 
                    [itemTransfer] => 
                    [vendorClaim] => 
                    [currentEstimatedLife] => 48
                    [locationId] => 2151
                    [deliveryPacking] => 
                    [residu] => 0
                    [estimatedLifeYear] => 4
                    [currentStartDate] => 14/12/2023
                    [assetAccountId] => 83
                    [transDate] => 14/12/2023
                    [disposed] => 
                    [currentAssetCost] => 20000000
                    [vendorPrice] => 
                    [estimatedLife] => 48
                    [salesReceipt] => 
                    [materialSlip] => 
                    [quantity] => 1
                    [sellingPriceAdjustment] => 
                    [deliveryOrder] => 
                    [materialAdjustment] => 
                    [usageDate] => 14/12/2023
                    [lastJournalDate] => 14/12/2023
                    [acmDepreciationAccountId] => 88
                    [purchaseOrder] => 
                    [fixedAsset] => 1
                    [purchaseReturn] => 
                    [standardProductCost] => 
                    [fiscalFaTypeId] => 
                )

            [1] => stdClass Object
                (
                    [intangible] => 
                    [assetCost] => 500000000
                    [notes] => 
                    [lastJournalDateView] => 14 Dec 2023
                    [depreciationMethod] => 
                    [departmentId] => 
                    [stockOpnameResult] => 
                    [optLock] => 0
                    [exchangeInvoice] => 
                    [depreciationAccountId] => 
                    [receiveItem] => 
                    [rollOver] => 
                    [currentStartDateView] => 14 Dec 2023
                    [manufactureOrder] => 
                    [number] => DFT.00003
                    [quantityDisposed] => 0
                    [itemAdjustment] => 
                    [draft] => 1
                    [depreciationRate] => 0
                    [id] => 51
                    [fiscalFa] => 
                    [transDateView] => 14 Dec 2023
                    [periodEnd] => 
                    [workOrder] => 
                    [branchId] => 50
                    [quantityAvailable] => 1
                    [assetTransfer] => 
                    [salesInvoice] => 
                    [billOfMaterial] => 
                    [stockOpnameOrder] => 
                    [purchaseInvoice] => 
                    [estimatedLifeMonth] => 0
                    [usageDateView] => 14 Dec 2023
                    [salesOrder] => 
                    [transferOrder] => 
                    [fixedAssetEdited] => 
                    [salesQuotation] => 
                    [employeePayment] => 
                    [faTypeId] => 
                    [expenseAccrual] => 
                    [salesReturn] => 
                    [purchaseRequisition] => 
                    [processStages] => 
                    [bankTransfer] => 
                    [finishedGoodSlip] => 
                    [journalId] => 
                    [purchasePayment] => 
                    [jobOrder] => 
                    [description] => Moulding Mesin
                    [otherDeposit] => 
                    [otherPayment] => 
                    [costDistribution] => 
                    [customerClaim] => 
                    [journal] => 
                    [itemTransfer] => 
                    [vendorClaim] => 
                    [currentEstimatedLife] => 0
                    [locationId] => 50
                    [deliveryPacking] => 
                    [residu] => 0
                    [estimatedLifeYear] => 0
                    [currentStartDate] => 14/12/2023
                    [assetAccountId] => 
                    [transDate] => 14/12/2023
                    [disposed] => 
                    [currentAssetCost] => 500000000
                    [vendorPrice] => 
                    [estimatedLife] => 0
                    [salesReceipt] => 
                    [materialSlip] => 
                    [quantity] => 1
                    [sellingPriceAdjustment] => 
                    [deliveryOrder] => 
                    [materialAdjustment] => 
                    [usageDate] => 14/12/2023
                    [lastJournalDate] => 14/12/2023
                    [acmDepreciationAccountId] => 
                    [purchaseOrder] => 
                    [fixedAsset] => 1
                    [purchaseReturn] => 
                    [standardProductCost] => 
                    [fiscalFaTypeId] => 
                )

            [2] => stdClass Object
                (
                    [intangible] => 
                    [assetCost] => 0
                    [notes] => 
                    [lastJournalDateView] => 13 Dec 2023
                    [depreciationMethod] => STRAIGHTLINE
                    [departmentId] => 
                    [stockOpnameResult] => 
                    [optLock] => 5
                    [exchangeInvoice] => 
                    [depreciationAccountId] => 2050
                    [receiveItem] => 
                    [rollOver] => 
                    [currentStartDateView] => 13 Dec 2023
                    [manufactureOrder] => 
                    [number] => FAA.2023.12.00002
                    [quantityDisposed] => 1
                    [itemAdjustment] => 
                    [draft] => 
                    [depreciationRate] => 12.5
                    [id] => 100
                    [fiscalFa] => 
                    [transDateView] => 13 Dec 2023
                    [periodEnd] => 
                    [workOrder] => 
                    [branchId] => 50
                    [quantityAvailable] => 0
                    [assetTransfer] => 
                    [salesInvoice] => 
                    [billOfMaterial] => 
                    [stockOpnameOrder] => 
                    [purchaseInvoice] => 
                    [estimatedLifeMonth] => 0
                    [usageDateView] => 13 Dec 2023
                    [salesOrder] => 
                    [transferOrder] => 
                    [fixedAssetEdited] => 
                    [salesQuotation] => 
                    [employeePayment] => 
                    [faTypeId] => 50
                    [expenseAccrual] => 
                    [salesReturn] => 
                    [purchaseRequisition] => 
                    [processStages] => 
                    [bankTransfer] => 
                    [finishedGoodSlip] => 
                    [journalId] => 3704
                    [purchasePayment] => 
                    [jobOrder] => 
                    [description] => moulding 2
                    [otherDeposit] => 
                    [otherPayment] => 
                    [costDistribution] => 
                    [customerClaim] => 
                    [journal] => 
                    [itemTransfer] => 
                    [vendorClaim] => 
                    [currentEstimatedLife] => 96
                    [locationId] => 2151
                    [deliveryPacking] => 
                    [residu] => 0
                    [estimatedLifeYear] => 8
                    [currentStartDate] => 13/12/2023
                    [assetAccountId] => 2000
                    [transDate] => 13/12/2023
                    [disposed] => 1
                    [currentAssetCost] => 0
                    [vendorPrice] => 
                    [estimatedLife] => 96
                    [salesReceipt] => 
                    [materialSlip] => 
                    [quantity] => 1
                    [sellingPriceAdjustment] => 
                    [deliveryOrder] => 
                    [materialAdjustment] => 
                    [usageDate] => 13/12/2023
                    [lastJournalDate] => 13/12/2023
                    [acmDepreciationAccountId] => 2100
                    [purchaseOrder] => 
                    [fixedAsset] => 1
                    [purchaseReturn] => 
                    [standardProductCost] => 
                    [fiscalFaTypeId] => 
                )

            [3] => stdClass Object
                (
                    [intangible] => 
                    [assetCost] => 300000000
                    [notes] => 
                    [lastJournalDateView] => 13 Dec 2023
                    [depreciationMethod] => STRAIGHTLINE
                    [departmentId] => 
                    [stockOpnameResult] => 
                    [optLock] => 0
                    [exchangeInvoice] => 
                    [depreciationAccountId] => 2050
                    [receiveItem] => 
                    [rollOver] => 
                    [currentStartDateView] => 13 Dec 2023
                    [manufactureOrder] => 
                    [number] => FAA.2023.12.00001
                    [quantityDisposed] => 0
                    [itemAdjustment] => 
                    [draft] => 
                    [depreciationRate] => 20
                    [id] => 50
                    [fiscalFa] => 
                    [transDateView] => 13 Dec 2023
                    [periodEnd] => 
                    [workOrder] => 
                    [branchId] => 50
                    [quantityAvailable] => 1
                    [assetTransfer] => 
                    [salesInvoice] => 
                    [billOfMaterial] => 
                    [stockOpnameOrder] => 
                    [purchaseInvoice] => 
                    [estimatedLifeMonth] => 0
                    [usageDateView] => 13 Dec 2023
                    [salesOrder] => 
                    [transferOrder] => 
                    [fixedAssetEdited] => 
                    [salesQuotation] => 
                    [employeePayment] => 
                    [faTypeId] => 50
                    [expenseAccrual] => 
                    [salesReturn] => 
                    [purchaseRequisition] => 
                    [processStages] => 
                    [bankTransfer] => 
                    [finishedGoodSlip] => 
                    [journalId] => 3651
                    [purchasePayment] => 
                    [jobOrder] => 
                    [description] => Moulding Mesin
                    [otherDeposit] => 
                    [otherPayment] => 
                    [costDistribution] => 
                    [customerClaim] => 
                    [journal] => 
                    [itemTransfer] => 
                    [vendorClaim] => 
                    [currentEstimatedLife] => 60
                    [locationId] => 50
                    [deliveryPacking] => 
                    [residu] => 0
                    [estimatedLifeYear] => 5
                    [currentStartDate] => 13/12/2023
                    [assetAccountId] => 2000
                    [transDate] => 13/12/2023
                    [disposed] => 
                    [currentAssetCost] => 300000000
                    [vendorPrice] => 
                    [estimatedLife] => 60
                    [salesReceipt] => 
                    [materialSlip] => 
                    [quantity] => 1
                    [sellingPriceAdjustment] => 
                    [deliveryOrder] => 
                    [materialAdjustment] => 
                    [usageDate] => 13/12/2023
                    [lastJournalDate] => 13/12/2023
                    [acmDepreciationAccountId] => 2100
                    [purchaseOrder] => 
                    [fixedAsset] => 1
                    [purchaseReturn] => 
                    [standardProductCost] => 
                    [fiscalFaTypeId] => 
                )

        )

    [sp] => stdClass Object
        (
            [page] => 1
            [sort] => 
            [pageSize] => 20
            [pageCount] => 1
            [rowCount] => 4
            [start] => 0
            [limit] => 
        )

)